import tkinter as tk

window = tk.Tk()
window.title("Profile Builder")
window.resizable(False,False)
window.configure(bg="pink",cursor="arrow")

title = tk.Label(text="Profile Builder",bg="pink",font="bold")
title.grid(row=0,column=0)

frame=tk.Frame(window,bg="lightblue")
frame.grid(padx=10)

name_label=tk.Label(frame,text="First Name",bg="lightblue")
name_label.grid(row=2,column=0)
name_entry=tk.Entry(frame)
name_entry.grid(row=1,column=0)
name_label=tk.Label(frame,text="Middle Name",bg="lightblue")
name_label.grid(row=2,column=1)
name_entry1=tk.Entry(frame)
name_entry1.grid(row=1,column=1)
name_label=tk.Label(frame,text="Last Name",bg="lightblue")
name_label.grid(row=2,column=2)
name_entry2=tk.Entry(frame)
name_entry2.grid(row=1,column=2)
name_label=tk.Label(frame,text="Birth Year",bg="lightblue")
name_label.grid(row=4,column=0)
name_entry3=tk.Entry(frame)
name_entry3.grid(row=3,column=0)
name_label=tk.Label(frame,text="Gender",bg="lightblue")
name_label.grid(row=5,column=0)
checkbutton=tk.Checkbutton(frame,text="Male",bg="lightblue")
checkbutton.grid(row=5,column=1)
checkbutton=tk.Checkbutton(frame,text="Female",bg="lightblue")
checkbutton.grid(row=5,column=2)
button=tk.Button(window,text="Submit",bg="Lightblue")
button.grid(row=5,column=0)
radio_button=tk.Radiobutton()
radio_button.grid()
second_window=tk.Toplevel()
second_window.title("Student ID")
second_window=tk.Frame()
window.mainloop()
